### ISSUE TITLE
Create API endpoint for cleanliness to enable APP to connect

### ISSUE THREAD

**Issue by jonathanba** [TU-CP18/cp18-backend#108]
**Description:**

**Acceptance criteria:**

- [ ]
- [ ]

**Comment by nschoen** [comment]
Simple CRUD with numbers should be fine. In a real application one would implement a kind of weighted average with never ratings having a higher weight and older ratings a lower weight. When the car is washed all previous rating will have weight 0.
The system would then probably propose a new wash depending of the time elapsed since the last wash, average cleanliness rating etc.... We could write about that in the final document.

For now we could also just use the issue tracking. Currently I use the prefixes "front", "driver", "rear", "coDriver" and "interior" in the `part` attribute of the issue. Maybe we can just use additionally "cleanlinessExterior" und "cleanlinessInterior" as other prefixes to track it. In the frontend (FM, SD) we can then just display the different issues/ratings depending on the `issue.part`.

**Comment by nschoen** [comment]
Attributes for the cleanliness endpoint:
- Number for the rating
- Related car
- Related Shift
- Boolean `preRide` ? to indicate that the cleanliness has been rated before or after the ride
